# Generated by Django 6.0.2 on 2026-03-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(auto_created=True, blank=True, max_length=200),
        ),
    ]
