# Generated by Django 6.0.2 on 2026-03-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_project_url_project_id_alter_project_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='manager_type',
            field=models.CharField(choices=[('zip', 'Zip')], default='zip', max_length=50),
        ),
    ]
